/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AvaliarRouteImport } from './routes/avaliar'
import { Route as BanheiroRouteImport } from './routes/banheiro'
import { Route as BotoesRouteImport } from './routes/botoes'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CodigoRouteImport } from './routes/codigo'
import { Route as CoreografiasRouteImport } from './routes/coreografias'
import { Route as DesignRouteImport } from './routes/design'
import { Route as EngenhariaRouteImport } from './routes/engenharia'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as MaterialRouteImport } from './routes/material'
import { Route as MelhoriasRouteImport } from './routes/melhorias'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PilotarRouteImport } from './routes/pilotar'
import { Route as PresencaRouteImport } from './routes/presenca'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as ProgramadorRouteImport } from './routes/programador'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as ProfessorIndexRouteImport } from './routes/professor.index'
import { Route as ProfessorAcompanhamentoRouteImport } from './routes/professor.acompanhamento'
import { Route as ProfessorAvaliacoesRouteImport } from './routes/professor.avaliacoes'
import { Route as ProfessorBanheiroRouteImport } from './routes/professor.banheiro'
import { Route as ProfessorCadastroRouteImport } from './routes/professor.cadastro'
import { Route as ProfessorMateriaisRouteImport } from './routes/professor.materiais'
import { Route as ProfessorPilotarRouteImport } from './routes/professor.pilotar'
import { Route as ProfessorEquipeIdRouteImport } from './routes/professor.equipe.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarRoute = AvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => rootRouteImport,
} as any)
const BanheiroRoute = BanheiroRouteImport.update({
  id: '/banheiro',
  path: '/banheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const BotoesRoute = BotoesRouteImport.update({
  id: '/botoes',
  path: '/botoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigoRoute = CodigoRouteImport.update({
  id: '/codigo',
  path: '/codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreografiasRoute = CoreografiasRouteImport.update({
  id: '/coreografias',
  path: '/coreografias',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaRoute = EngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRoute = MaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoriasRoute = MelhoriasRouteImport.update({
  id: '/melhorias',
  path: '/melhorias',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotarRoute = PilotarRouteImport.update({
  id: '/pilotar',
  path: '/pilotar',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencaRoute = PresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramadorRoute = ProgramadorRouteImport.update({
  id: '/programador',
  path: '/programador',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorIndexRoute = ProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorAcompanhamentoRoute = ProfessorAcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorAvaliacoesRoute = ProfessorAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorBanheiroRoute = ProfessorBanheiroRouteImport.update({
  id: '/banheiro',
  path: '/banheiro',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorCadastroRoute = ProfessorCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorMateriaisRoute = ProfessorMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorPilotarRoute = ProfessorPilotarRouteImport.update({
  id: '/pilotar',
  path: '/pilotar',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorEquipeIdRoute = ProfessorEquipeIdRouteImport.update({
  id: '/equipe/$id',
  path: '/equipe/$id',
  getParentRoute: () => ProfessorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/avaliar': typeof AvaliarRoute
  '/banheiro': typeof BanheiroRoute
  '/botoes': typeof BotoesRoute
  '/checklist': typeof ChecklistRoute
  '/codigo': typeof CodigoRoute
  '/coreografias': typeof CoreografiasRoute
  '/design': typeof DesignRoute
  '/engenharia': typeof EngenhariaRoute
  '/equipe': typeof EquipeRoute
  '/material': typeof MaterialRoute
  '/melhorias': typeof MelhoriasRoute
  '/painel': typeof PainelRoute
  '/pilotar': typeof PilotarRoute
  '/presenca': typeof PresencaRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/programador': typeof ProgramadorRoute
  '/tutorial': typeof TutorialRoute
  '/professor/acompanhamento': typeof ProfessorAcompanhamentoRoute
  '/professor/avaliacoes': typeof ProfessorAvaliacoesRoute
  '/professor/banheiro': typeof ProfessorBanheiroRoute
  '/professor/cadastro': typeof ProfessorCadastroRoute
  '/professor/materiais': typeof ProfessorMateriaisRoute
  '/professor/pilotar': typeof ProfessorPilotarRoute
  '/professor/': typeof ProfessorIndexRoute
  '/professor/equipe/$id': typeof ProfessorEquipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/avaliar': typeof AvaliarRoute
  '/banheiro': typeof BanheiroRoute
  '/botoes': typeof BotoesRoute
  '/checklist': typeof ChecklistRoute
  '/codigo': typeof CodigoRoute
  '/coreografias': typeof CoreografiasRoute
  '/design': typeof DesignRoute
  '/engenharia': typeof EngenhariaRoute
  '/equipe': typeof EquipeRoute
  '/material': typeof MaterialRoute
  '/melhorias': typeof MelhoriasRoute
  '/painel': typeof PainelRoute
  '/pilotar': typeof PilotarRoute
  '/presenca': typeof PresencaRoute
  '/programador': typeof ProgramadorRoute
  '/tutorial': typeof TutorialRoute
  '/professor/acompanhamento': typeof ProfessorAcompanhamentoRoute
  '/professor/avaliacoes': typeof ProfessorAvaliacoesRoute
  '/professor/banheiro': typeof ProfessorBanheiroRoute
  '/professor/cadastro': typeof ProfessorCadastroRoute
  '/professor/materiais': typeof ProfessorMateriaisRoute
  '/professor/pilotar': typeof ProfessorPilotarRoute
  '/professor': typeof ProfessorIndexRoute
  '/professor/equipe/$id': typeof ProfessorEquipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/avaliar': typeof AvaliarRoute
  '/banheiro': typeof BanheiroRoute
  '/botoes': typeof BotoesRoute
  '/checklist': typeof ChecklistRoute
  '/codigo': typeof CodigoRoute
  '/coreografias': typeof CoreografiasRoute
  '/design': typeof DesignRoute
  '/engenharia': typeof EngenhariaRoute
  '/equipe': typeof EquipeRoute
  '/material': typeof MaterialRoute
  '/melhorias': typeof MelhoriasRoute
  '/painel': typeof PainelRoute
  '/pilotar': typeof PilotarRoute
  '/presenca': typeof PresencaRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/programador': typeof ProgramadorRoute
  '/tutorial': typeof TutorialRoute
  '/professor/acompanhamento': typeof ProfessorAcompanhamentoRoute
  '/professor/avaliacoes': typeof ProfessorAvaliacoesRoute
  '/professor/banheiro': typeof ProfessorBanheiroRoute
  '/professor/cadastro': typeof ProfessorCadastroRoute
  '/professor/materiais': typeof ProfessorMateriaisRoute
  '/professor/pilotar': typeof ProfessorPilotarRoute
  '/professor/': typeof ProfessorIndexRoute
  '/professor/equipe/$id': typeof ProfessorEquipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/avaliar'
    | '/banheiro'
    | '/botoes'
    | '/checklist'
    | '/codigo'
    | '/coreografias'
    | '/design'
    | '/engenharia'
    | '/equipe'
    | '/material'
    | '/melhorias'
    | '/painel'
    | '/pilotar'
    | '/presenca'
    | '/professor'
    | '/programador'
    | '/tutorial'
    | '/professor/acompanhamento'
    | '/professor/avaliacoes'
    | '/professor/banheiro'
    | '/professor/cadastro'
    | '/professor/materiais'
    | '/professor/pilotar'
    | '/professor/'
    | '/professor/equipe/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/avaliar'
    | '/banheiro'
    | '/botoes'
    | '/checklist'
    | '/codigo'
    | '/coreografias'
    | '/design'
    | '/engenharia'
    | '/equipe'
    | '/material'
    | '/melhorias'
    | '/painel'
    | '/pilotar'
    | '/presenca'
    | '/programador'
    | '/tutorial'
    | '/professor/acompanhamento'
    | '/professor/avaliacoes'
    | '/professor/banheiro'
    | '/professor/cadastro'
    | '/professor/materiais'
    | '/professor/pilotar'
    | '/professor'
    | '/professor/equipe/$id'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/avaliar'
    | '/banheiro'
    | '/botoes'
    | '/checklist'
    | '/codigo'
    | '/coreografias'
    | '/design'
    | '/engenharia'
    | '/equipe'
    | '/material'
    | '/melhorias'
    | '/painel'
    | '/pilotar'
    | '/presenca'
    | '/professor'
    | '/programador'
    | '/tutorial'
    | '/professor/acompanhamento'
    | '/professor/avaliacoes'
    | '/professor/banheiro'
    | '/professor/cadastro'
    | '/professor/materiais'
    | '/professor/pilotar'
    | '/professor/'
    | '/professor/equipe/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AvaliarRoute: typeof AvaliarRoute
  BanheiroRoute: typeof BanheiroRoute
  BotoesRoute: typeof BotoesRoute
  ChecklistRoute: typeof ChecklistRoute
  CodigoRoute: typeof CodigoRoute
  CoreografiasRoute: typeof CoreografiasRoute
  DesignRoute: typeof DesignRoute
  EngenhariaRoute: typeof EngenhariaRoute
  EquipeRoute: typeof EquipeRoute
  MaterialRoute: typeof MaterialRoute
  MelhoriasRoute: typeof MelhoriasRoute
  PainelRoute: typeof PainelRoute
  PilotarRoute: typeof PilotarRoute
  PresencaRoute: typeof PresencaRoute
  ProfessorRoute: typeof ProfessorRouteWithChildren
  ProgramadorRoute: typeof ProgramadorRoute
  TutorialRoute: typeof TutorialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar': {
      id: '/avaliar'
      path: '/avaliar'
      fullPath: '/avaliar'
      preLoaderRoute: typeof AvaliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banheiro': {
      id: '/banheiro'
      path: '/banheiro'
      fullPath: '/banheiro'
      preLoaderRoute: typeof BanheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/botoes': {
      id: '/botoes'
      path: '/botoes'
      fullPath: '/botoes'
      preLoaderRoute: typeof BotoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo': {
      id: '/codigo'
      path: '/codigo'
      fullPath: '/codigo'
      preLoaderRoute: typeof CodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coreografias': {
      id: '/coreografias'
      path: '/coreografias'
      fullPath: '/coreografias'
      preLoaderRoute: typeof CoreografiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia': {
      id: '/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof EngenhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material': {
      id: '/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof MaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhorias': {
      id: '/melhorias'
      path: '/melhorias'
      fullPath: '/melhorias'
      preLoaderRoute: typeof MelhoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilotar': {
      id: '/pilotar'
      path: '/pilotar'
      fullPath: '/pilotar'
      preLoaderRoute: typeof PilotarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presenca': {
      id: '/presenca'
      path: '/presenca'
      fullPath: '/presenca'
      preLoaderRoute: typeof PresencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programador': {
      id: '/programador'
      path: '/programador'
      fullPath: '/programador'
      preLoaderRoute: typeof ProgramadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/': {
      id: '/professor/'
      path: '/'
      fullPath: '/professor/'
      preLoaderRoute: typeof ProfessorIndexRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/acompanhamento': {
      id: '/professor/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/professor/acompanhamento'
      preLoaderRoute: typeof ProfessorAcompanhamentoRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/avaliacoes': {
      id: '/professor/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/professor/avaliacoes'
      preLoaderRoute: typeof ProfessorAvaliacoesRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/banheiro': {
      id: '/professor/banheiro'
      path: '/banheiro'
      fullPath: '/professor/banheiro'
      preLoaderRoute: typeof ProfessorBanheiroRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/cadastro': {
      id: '/professor/cadastro'
      path: '/cadastro'
      fullPath: '/professor/cadastro'
      preLoaderRoute: typeof ProfessorCadastroRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/materiais': {
      id: '/professor/materiais'
      path: '/materiais'
      fullPath: '/professor/materiais'
      preLoaderRoute: typeof ProfessorMateriaisRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/pilotar': {
      id: '/professor/pilotar'
      path: '/pilotar'
      fullPath: '/professor/pilotar'
      preLoaderRoute: typeof ProfessorPilotarRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/equipe/$id': {
      id: '/professor/equipe/$id'
      path: '/equipe/$id'
      fullPath: '/professor/equipe/$id'
      preLoaderRoute: typeof ProfessorEquipeIdRouteImport
      parentRoute: typeof ProfessorRoute
    }
  }
}

interface ProfessorRouteChildren {
  ProfessorAcompanhamentoRoute: typeof ProfessorAcompanhamentoRoute
  ProfessorAvaliacoesRoute: typeof ProfessorAvaliacoesRoute
  ProfessorBanheiroRoute: typeof ProfessorBanheiroRoute
  ProfessorCadastroRoute: typeof ProfessorCadastroRoute
  ProfessorMateriaisRoute: typeof ProfessorMateriaisRoute
  ProfessorPilotarRoute: typeof ProfessorPilotarRoute
  ProfessorIndexRoute: typeof ProfessorIndexRoute
  ProfessorEquipeIdRoute: typeof ProfessorEquipeIdRoute
}

const ProfessorRouteChildren: ProfessorRouteChildren = {
  ProfessorAcompanhamentoRoute: ProfessorAcompanhamentoRoute,
  ProfessorAvaliacoesRoute: ProfessorAvaliacoesRoute,
  ProfessorBanheiroRoute: ProfessorBanheiroRoute,
  ProfessorCadastroRoute: ProfessorCadastroRoute,
  ProfessorMateriaisRoute: ProfessorMateriaisRoute,
  ProfessorPilotarRoute: ProfessorPilotarRoute,
  ProfessorIndexRoute: ProfessorIndexRoute,
  ProfessorEquipeIdRoute: ProfessorEquipeIdRoute,
}

const ProfessorRouteWithChildren = ProfessorRoute._addFileChildren(
  ProfessorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AvaliarRoute: AvaliarRoute,
  BanheiroRoute: BanheiroRoute,
  BotoesRoute: BotoesRoute,
  ChecklistRoute: ChecklistRoute,
  CodigoRoute: CodigoRoute,
  CoreografiasRoute: CoreografiasRoute,
  DesignRoute: DesignRoute,
  EngenhariaRoute: EngenhariaRoute,
  EquipeRoute: EquipeRoute,
  MaterialRoute: MaterialRoute,
  MelhoriasRoute: MelhoriasRoute,
  PainelRoute: PainelRoute,
  PilotarRoute: PilotarRoute,
  PresencaRoute: PresencaRoute,
  ProfessorRoute: ProfessorRouteWithChildren,
  ProgramadorRoute: ProgramadorRoute,
  TutorialRoute: TutorialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
