/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CodigoRouteImport } from './routes/codigo'
import { Route as CoreografiasRouteImport } from './routes/coreografias'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as MelhoriasRouteImport } from './routes/melhorias'
import { Route as PainelRouteImport } from './routes/painel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigoRoute = CodigoRouteImport.update({
  id: '/codigo',
  path: '/codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreografiasRoute = CoreografiasRouteImport.update({
  id: '/coreografias',
  path: '/coreografias',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoriasRoute = MelhoriasRouteImport.update({
  id: '/melhorias',
  path: '/melhorias',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/codigo': typeof CodigoRoute
  '/coreografias': typeof CoreografiasRoute
  '/equipe': typeof EquipeRoute
  '/melhorias': typeof MelhoriasRoute
  '/painel': typeof PainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/codigo': typeof CodigoRoute
  '/coreografias': typeof CoreografiasRoute
  '/equipe': typeof EquipeRoute
  '/melhorias': typeof MelhoriasRoute
  '/painel': typeof PainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/codigo': typeof CodigoRoute
  '/coreografias': typeof CoreografiasRoute
  '/equipe': typeof EquipeRoute
  '/melhorias': typeof MelhoriasRoute
  '/painel': typeof PainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/codigo'
    | '/coreografias'
    | '/equipe'
    | '/melhorias'
    | '/painel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/codigo'
    | '/coreografias'
    | '/equipe'
    | '/melhorias'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/codigo'
    | '/coreografias'
    | '/equipe'
    | '/melhorias'
    | '/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  CodigoRoute: typeof CodigoRoute
  CoreografiasRoute: typeof CoreografiasRoute
  EquipeRoute: typeof EquipeRoute
  MelhoriasRoute: typeof MelhoriasRoute
  PainelRoute: typeof PainelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo': {
      id: '/codigo'
      path: '/codigo'
      fullPath: '/codigo'
      preLoaderRoute: typeof CodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coreografias': {
      id: '/coreografias'
      path: '/coreografias'
      fullPath: '/coreografias'
      preLoaderRoute: typeof CoreografiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhorias': {
      id: '/melhorias'
      path: '/melhorias'
      fullPath: '/melhorias'
      preLoaderRoute: typeof MelhoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  CodigoRoute: CodigoRoute,
  CoreografiasRoute: CoreografiasRoute,
  EquipeRoute: EquipeRoute,
  MelhoriasRoute: MelhoriasRoute,
  PainelRoute: PainelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
